// Code generated by sqlc. DO NOT EDIT.

package db

import "database/sql"

type DBTX interface {
	ExecContext(ctx interface{}, query string, args ...interface{}) (sql.Result, error)
	QueryContext(ctx interface{}, query string, args ...interface{}) (*sql.Rows, error)
	QueryRowContext(ctx interface{}, query string, args ...interface{}) *sql.Row
}

type Queries struct {
	db *sql.DB
}

func New(db *sql.DB) *Queries {
	return &Queries{db: db}
}
