// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"time"
)

type CreateUserParams struct {
	Name string    `json:"name"`
	Dob  time.Time `json:"dob"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx,
		`INSERT INTO users (name, dob) VALUES ($1, $2) RETURNING id, name, dob`,
		arg.Name, arg.Dob,
	)
	var u User
	err := row.Scan(&u.ID, &u.Name, &u.Dob)
	return u, err
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx,
		`SELECT id, name, dob FROM users WHERE id = $1`, id,
	)
	var u User
	err := row.Scan(&u.ID, &u.Name, &u.Dob)
	return u, err
}

type UpdateUserParams struct {
	Name string    `json:"name"`
	Dob  time.Time `json:"dob"`
	ID   int32     `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx,
		`UPDATE users SET name=$1, dob=$2 WHERE id=$3 RETURNING id, name, dob`,
		arg.Name, arg.Dob, arg.ID,
	)
	var u User
	err := row.Scan(&u.ID, &u.Name, &u.Dob)
	return u, err
}

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, `DELETE FROM users WHERE id = $1`, id)
	return err
}

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx,
		`SELECT id, name, dob FROM users ORDER BY id ASC LIMIT $1 OFFSET $2`,
		arg.Limit, arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var users []User
	for rows.Next() {
		var u User
		if err := rows.Scan(&u.ID, &u.Name, &u.Dob); err != nil {
			return nil, err
		}
		users = append(users, u)
	}
	if users == nil {
		return []User{}, nil
	}
	return users, rows.Err()
}

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	var count int64
	err := q.db.QueryRowContext(ctx, `SELECT COUNT(*) FROM users`).Scan(&count)
	return count, err
}
